### ISSUE TITLE
[BUG]in 'example.py'

### ISSUE THREAD

**Issue by KurokoWD** [kyegomez/PALI3#6]
Hello
I meet a bug in example.py,after 'python example.py',it reported 'stop_sequences: list[str] = field(
TypeError: 'type' object is not subscriptable'
Can you help me?

**Comment by Haonote** [comment]
I meet the same problem，Did you solve this problem

**Comment by kyegomez** [comment]
@KurokoWD @Haonote can you provide the full output?

**Comment by KurokoWD** [comment]
@kyegomez 
Thanks to your reply.
My full output is as follow:

_____________________________________
\____    /\_   _____/\__    ___/  _    /     /  |    __)_   |    | /  /_\   /     /_  |        \  |    |/    |    /_______ \/_______  /  |____|\____|__  /
        \/        \/                 \/

Traceback (most recent call last):
  File "example.py", line 2, in <module>
    from pali3.main import Pali3
  File "/home/weidong/PALI3-main/pali3/__init__.py", line 1, in <module>
    from pali3.tokenizer import tokenize, detokenize
  File "/home/weidong/PALI3-main/pali3/tokenizer.py", line 2, in <module>
    from zeta.tokenizers import TokenMonster
  File "/home/weidong/anaconda3/envs/pytorch/lib/python3.8/site-packages/zeta/__init__.py", line 37, in <module>
    from zeta import tokenizers
  File "/home/weidong/anaconda3/envs/pytorch/lib/python3.8/site-packages/zeta/tokenizers/__init__.py", line 5, in <module>
    from zeta.tokenizers.tiktoken import TikToken
  File "/home/weidong/anaconda3/envs/pytorch/lib/python3.8/site-packages/zeta/tokenizers/tiktoken.py", line 8, in <module>
    from zeta.tokenizers.base import BaseTokenizer
  File "/home/weidong/anaconda3/envs/pytorch/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 9, in <module>
    class BaseTokenizer(ABC):
  File "/home/weidong/anaconda3/envs/pytorch/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 12, in BaseTokenizer
    stop_sequences: list[str] = field(
TypeError: 'type' object is not subscriptable

**Comment by Haonote** [comment]
@kyegomez Thanks to your reply
My error report is as follows：

_____________________________________
\____    /\_   _____/\__    ___/  _    /     /  |    __)_   |    | /  /_\   /     /_  |        \  |    |/    |    /_______ \/_______  /  |____|\____|__  /
        \/        \/                 \/

Traceback (most recent call last):
  File "/home/hao/下载/PALI3-main/example.py", line 2, in <module>
    from pali3.main import Pali3
  File "/home/hao/下载/PALI3-main/pali3/__init__.py", line 1, in <module>
    from pali3.tokenizer import tokenize, detokenize
  File "/home/hao/下载/PALI3-main/pali3/tokenizer.py", line 2, in <module>
    from zeta.tokenizers import TokenMonster
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/__init__.py", line 37, in <module>
    from zeta import tokenizers
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/__init__.py", line 5, in <module>
    from zeta.tokenizers.tiktoken import TikToken
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/tiktoken.py", line 8, in <module>
    from zeta.tokenizers.base import BaseTokenizer
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 9, in <module>
    class BaseTokenizer(ABC):
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 12, in BaseTokenizer
    stop_sequences: list[str] = field(
TypeError: 'type' object is not subscriptable

Process finished with exit code 1

**Comment by Haonote** [comment]
@kyegomez @KurokoWD 
 More information，I accidentally used python in terminal to try to import this library and the error is the same, but before running the code and showing the error of importing the library
(venv) hao@ubuntu:~/下载/PALI3-main$ python
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from zeta.tokenizers import TokenMonster

_____________________________________
\____    /\_   _____/\__    ___/  _    /     /  |    __)_   |    | /  /_\   /     /_  |        \  |    |/    |    /_______ \/_______  /  |____|\____|__  /
        \/        \/                 \/

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/__init__.py", line 37, in <module>
    from zeta import tokenizers
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/__init__.py", line 5, in <module>
    from zeta.tokenizers.tiktoken import TikToken
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/tiktoken.py", line 8, in <module>
    from zeta.tokenizers.base import BaseTokenizer
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 9, in <module>
    class BaseTokenizer(ABC):
  File "/home/hao/下载/PALI3-main/venv/lib/python3.8/site-packages/zeta/tokenizers/base.py", line 12, in BaseTokenizer
    stop_sequences: list[str] = field(
TypeError: 'type' object is not subscriptable

**Comment by KurokoWD** [comment]
@Haonote 
Yes, it looks like the problem is with zeta.tokenizer, it might be related to the compatibility of some packages, hopefully the author will come up with a more detailed file about environment configuration.

**Comment by kyegomez** [comment]
@KurokoWD its fixed now please try again and let me know
